### PR TITLE
Css

### PR DESCRIPTION
**Pull request by BSGreaves**
Assignment complete

### CODE REVIEW

**Review by DevDreed — CHANGES_REQUESTED** [review]
Validate Telephone input.

**Comment by BSGreaves** [comment]
Technically it's not a requirement - it had to validate "when a valid web URL or email address is entered into the corresponding field".

**Comment by DevDreed** [comment]
It should at least have the correct input type for telephone.

**Review by DevDreed — APPROVED** [review]
Looks good

**Pull request merged**
